
server:
    port: 8090

redisson:
    address: redis://127.0.0.1:6379
    password: 123456
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3000

